// packages/react/src/index.tsx
import {
  createContext,
  useContext,
  useState,
  useCallback,
  useMemo,
} from "react";
import type { ReactNode } from "react";
import {
  PasskeyClient,
  type RegistrationResult,
  type AuthenticationResult,
} from "@open-passkey/sdk";

type Status = "idle" | "pending" | "success" | "error";

const PasskeyContext = createContext<PasskeyClient | null>(null);

function useClient(): PasskeyClient {
  const client = useContext(PasskeyContext);
  if (!client) {
    throw new Error(
      "usePasskeyRegister/usePasskeyLogin must be used within a <PasskeyProvider>"
    );
  }
  return client;
}

export interface PasskeyProviderProps {
  baseUrl: string;
  children: ReactNode;
}

export function PasskeyProvider({ baseUrl, children }: PasskeyProviderProps) {
  const client = useMemo(() => new PasskeyClient({ baseUrl }), [baseUrl]);

  return (
    <PasskeyContext.Provider value={client}>
      {children}
    </PasskeyContext.Provider>
  );
}

export function usePasskeyRegister() {
  const client = useClient();
  const [status, setStatus] = useState<Status>("idle");
  const [result, setResult] = useState<RegistrationResult | null>(null);
  const [error, setError] = useState<Error | null>(null);

  const register = useCallback(
    async (userId: string, username: string) => {
      setStatus("pending");
      setResult(null);
      setError(null);
      try {
        const res = await client.register(userId, username);
        setResult(res);
        setStatus("success");
      } catch (err) {
        setError(err instanceof Error ? err : new Error(String(err)));
        setStatus("error");
      }
    },
    [client]
  );

  return { register, status, result, error };
}

export function usePasskeyLogin() {
  const client = useClient();
  const [status, setStatus] = useState<Status>("idle");
  const [result, setResult] = useState<AuthenticationResult | null>(null);
  const [error, setError] = useState<Error | null>(null);

  const authenticate = useCallback(
    async (userId?: string) => {
      setStatus("pending");
      setResult(null);
      setError(null);
      try {
        const res = await client.authenticate(userId);
        setResult(res);
        setStatus("success");
      } catch (err) {
        setError(err instanceof Error ? err : new Error(String(err)));
        setStatus("error");
      }
    },
    [client]
  );

  return { authenticate, status, result, error };
}

// packages/solid/src/index.tsx
import {
  createSignal,
  createContext,
  useContext,
  type Accessor,
  type JSX,
} from "solid-js";
import {
  PasskeyClient,
  type RegistrationResult,
  type AuthenticationResult,
} from "@open-passkey/sdk";

type Status = "idle" | "pending" | "success" | "error";

const PasskeyContext = createContext<PasskeyClient>();

export interface PasskeyProviderProps {
  baseUrl: string;
  children: JSX.Element;
}

export function PasskeyProvider(props: PasskeyProviderProps) {
  const client = new PasskeyClient({ baseUrl: props.baseUrl });

  return (
    <PasskeyContext.Provider value={client}>
      {props.children}
    </PasskeyContext.Provider>
  );
}

function useClient(): PasskeyClient {
  const client = useContext(PasskeyContext);
  if (!client) {
    throw new Error(
      "createPasskeyRegister/createPasskeyLogin must be used within a <PasskeyProvider>"
    );
  }
  return client;
}

export function createPasskeyRegister() {
  const client = useClient();
  const [status, setStatus] = createSignal<Status>("idle");
  const [result, setResult] = createSignal<RegistrationResult | null>(null);
  const [error, setError] = createSignal<Error | null>(null);

  async function register(userId: string, username: string): Promise<void> {
    setStatus("pending");
    setResult(null);
    setError(null);
    try {
      const res = await client.register(userId, username);
      setResult(res);
      setStatus("success");
    } catch (err) {
      setError(err instanceof Error ? err : new Error(String(err)));
      setStatus("error");
    }
  }

  return { register, status: status as Accessor<Status>, result: result as Accessor<RegistrationResult | null>, error: error as Accessor<Error | null> };
}

export function createPasskeyLogin() {
  const client = useClient();
  const [status, setStatus] = createSignal<Status>("idle");
  const [result, setResult] = createSignal<AuthenticationResult | null>(null);
  const [error, setError] = createSignal<Error | null>(null);

  async function authenticate(userId?: string): Promise<void> {
    setStatus("pending");
    setResult(null);
    setError(null);
    try {
      const res = await client.authenticate(userId);
      setResult(res);
      setStatus("success");
    } catch (err) {
      setError(err instanceof Error ? err : new Error(String(err)));
      setStatus("error");
    }
  }

  return { authenticate, status: status as Accessor<Status>, result: result as Accessor<AuthenticationResult | null>, error: error as Accessor<Error | null> };
}
